export const ALL_RESTAURANTS_REQUEST = "ALL_RESTAURANT_REQUEST";
export const ALL_RESTAURANTS_SUCCESS = "ALL_RESTAURANT_SUCCESS";

export const ALL_RESTAURANTS_FAIL = "ALL_RESTAURANTS_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const SORT_BY_RATINGS = "SORT_BY_RATINGS";
export const SORT_BY_REVIEWS = "SORT_BY_REVIEWS";
export const TOGGLE_VEG_ONLY = "TOGGLE_VEG_ONLY";
